name: Multi Job Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'multi_job_pipeline/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: multi_job_pipeline

    steps:
      - uses: actions/checkout@v4
      - run: npm install
      - run: npm run build

  test:
    runs-on: ubuntu-latest
    needs: build
    defaults:
      run:
        working-directory: multi_job_pipeline

    steps:
      - uses: actions/checkout@v4
      - run: npm install
      - run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - run: echo "Deploying application 🚀"
