name: Test on PR

on:
  pull_request:
    branches:
      - main
    paths:
      - 'test_on_PR/**'

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: test_on_PR

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test
